version: '3'
services:
  django:
    platform: linux/amd64
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      IS_DEBUG: "TRUE"
  nginx:
    volumes:
      - ./nginx/sites-enabled-dev:/etc/nginx/sites-enabled
  postgres:
    ports:
      - "5432:5432"
  frontend:
    command: npm run dev
    ports:
      - "8080:8080"