version: '3'
services:
  django:
    platform: linux/amd64
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      IS_DEBUG: "TRUE"
    restart: "no"

  nginx:
    volumes:
      - ./nginx/sites-enabled-dev:/etc/nginx/sites-enabled
    restart: "no"

  postgres:
    ports:
      - 5432:5432
    restart: "no"

  frontend:
    ports:
      - 8080:8080
