# Generated by Django 4.0.3 on 2022-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('ISPDN', 'ИСПДн'), ('ASUTP', 'АСУТП')], max_length=8, verbose_name='Тип')),
                ('assets', models.ManyToManyField(to='app.asset', verbose_name='Объекты')),
                ('negative_consequences', models.ManyToManyField(to='app.negativeconsequence', verbose_name='Негативные последствия')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
    ]
