# Generated by Django 4.0.4 on 2022-04-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_systemclass_alter_scenariostep_step_number'),
        ('users_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='type',
        ),
        migrations.AddField(
            model_name='system',
            name='system_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.systemclass', verbose_name='Класс системы'),
        ),
    ]
