# Generated by Django 4.0.4 on 2022-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asutpclass_specification_and_more'),
        ('users_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='negative_consequences',
            field=models.ManyToManyField(to='app.negativeconsequence', verbose_name='Негативные последствия'),
        ),
    ]
