# Generated by Django 4.0.5 on 2022-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_interface_asset_type_assettype_interfaces_and_more'),
        ('users_system', '0002_system_negative_consequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='asutp_classes',
            field=models.ManyToManyField(blank=True, to='app.asutpclass', verbose_name='Классы АСУТП'),
        ),
        migrations.AlterField(
            model_name='system',
            name='gis_classes',
            field=models.ManyToManyField(blank=True, to='app.gisclass', verbose_name='Классы ГИС'),
        ),
        migrations.AlterField(
            model_name='system',
            name='ispdn_classes',
            field=models.ManyToManyField(blank=True, to='app.ispdnclass', verbose_name='Классы ИСПДн'),
        ),
        migrations.AlterField(
            model_name='system',
            name='kii_classes',
            field=models.ManyToManyField(blank=True, to='app.kiiclass', verbose_name='Классы КИИ'),
        ),
    ]
