# Generated by Django 4.0.5 on 2022-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_asutpclass_specification'),
        ('users_system', '0003_alter_system_asutp_classes_alter_system_gis_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='assets',
            field=models.ManyToManyField(blank=True, to='app.asset', verbose_name='Объекты'),
        ),
        migrations.AlterField(
            model_name='system',
            name='negative_consequences',
            field=models.ManyToManyField(blank=True, to='app.negativeconsequence', verbose_name='Негативные последствия'),
        ),
    ]
