# Generated by Django 4.0.2 on 2022-02-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Возможность нарушителя',
                'verbose_name_plural': 'Возможности нарушителя',
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'verbose_name': 'Интерфейс', 'verbose_name_plural': 'Интерфейсы'},
        ),
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('INSIDER', 'Внутренний'), ('OUTSIDER', 'Внешний')], default='INSIDER', max_length=8, verbose_name='Тип')),
                ('capabilities', models.ManyToManyField(to='app.Capabilities')),
            ],
            options={
                'verbose_name': 'Нарушитель',
                'verbose_name_plural': 'Нарушители',
            },
        ),
    ]
