# Generated by Django 4.0.4 on 2022-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_scenariostep_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Название')),
                ('type', models.CharField(choices=[('ISPDN', 'ИСПДн'), ('GIS', 'ГИС'), ('ASUTP', 'АСУТП'), ('KI_OBJECT', 'Объект КИ')], default='ISPDN', max_length=9, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='step_number',
            field=models.IntegerField(verbose_name='Номер шага'),
        ),
    ]
