# Generated by Django 4.0.2 on 2022-02-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capabilities_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacker',
            name='capabilities',
            field=models.ManyToManyField(related_name='Возможности', to='app.Capabilities'),
        ),
    ]
