# Generated by Django 4.0.2 on 2022-02-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attacker_capabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilities',
            name='name',
        ),
        migrations.AddField(
            model_name='capabilities',
            name='level',
            field=models.CharField(choices=[('N4', 'Н4'), ('N3', 'Н3'), ('N2', 'Н2'), ('N1', 'Н1')], default='N4', max_length=2, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='capabilities',
            name='potential',
            field=models.CharField(choices=[('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('LOW', 'Низкий')], default='LOW', max_length=8, verbose_name='Потенциал'),
        ),
        migrations.AlterField(
            model_name='attacker',
            name='capabilities',
            field=models.ManyToManyField(to='app.Capabilities', verbose_name='Возможности'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asset', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('INSIDER', 'Внутренний'), ('OUTSIDER', 'Внешний')], default='INSIDER', max_length=8, verbose_name='Тип')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.interface', verbose_name='Интерфейс')),
            ],
            options={
                'verbose_name': 'Уязвимость',
                'verbose_name_plural': 'Уязвимости',
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('potential', models.CharField(choices=[('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('LOW', 'Низкий')], default='LOW', max_length=8, verbose_name='Потенциал')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.vulnerability', verbose_name='Уязвимость')),
            ],
            options={
                'verbose_name': 'Угроза',
                'verbose_name_plural': 'Угрозы',
            },
        ),
    ]
