# Generated by Django 4.0.4 on 2022-05-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_asutpclass_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asutpclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('GOVERNMENT', 'Государственная'), ('BASIC', 'Базовая'), ('MANUFACTURE', 'Производство')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='gisclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('GOVERNMENT', 'Государственная'), ('BASIC', 'Базовая')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='ispdnclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('GOVERNMENT', 'Государственная'), ('BASIC', 'Базовая')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='kiiclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('GOVERNMENT', 'Государственная'), ('BASIC', 'Базовая')], max_length=44, verbose_name='Спецификация'),
        ),
    ]
