# Generated by Django 4.0.4 on 2022-05-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_asutpclass_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technique',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
