# Generated by Django 4.0.4 on 2022-06-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tactic_number_technique_number'),
    ]

    def createThreatsImplementationMethodGroup(apps, schema_editor):
        ThreatsImplementationMethodGroup = apps.get_model("app", "ThreatsImplementationMethodGroup")
        db_alias = schema_editor.connection.alias
        ThreatsImplementationMethodGroup.objects.using(db_alias).bulk_create([
            ThreatsImplementationMethodGroup(name="Группа1", number=1),
        ])

    operations = [
        migrations.CreateModel(
            name='ThreatsImplementationMethodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.SmallIntegerField(verbose_name='Номер группы')),
            ],
            options={
                'verbose_name': 'Группа способов реализации угроз',
                'verbose_name_plural': 'Группы способов реализации угроз',
            },
        ),
        migrations.RunPython(createThreatsImplementationMethodGroup, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='threatsimplementationmethod',
            name='description',
        ),
        migrations.AddField(
            model_name='threatsimplementationmethod',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatsimplementationmethod',
            name='threats',
            field=models.ManyToManyField(to='app.threat', verbose_name='Угрозы'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='bdu_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор УБИ'),
        ),
        migrations.AddField(
            model_name='threatsimplementationmethod',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.threatsimplementationmethodgroup', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
