# Generated by Django 4.0.4 on 2022-06-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_threatsimplementationmethodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='capability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.capability', verbose_name='Возможность нарушителя'),
        ),
        migrations.AddField(
            model_name='technique',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interface', verbose_name='Интерфейс'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='level',
            field=models.IntegerField(choices=[(4, 'Н4'), (3, 'Н3'), (2, 'Н2'), (1, 'Н1')], max_length=2, null=True, verbose_name='Уровень'),
        ),
    ]
