# Generated by Django 4.0.5 on 2022-06-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_interface_asset_type_assettype_interfaces_and_more'),
    ]

    def create_scope(apps, schema_editor):
        Scope = apps.get_model("app", "Scope")
        db_alias = schema_editor.connection.alias
        Scope.objects.using(db_alias).bulk_create([
            Scope(name="FirstScope"),
        ])

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Возможная цель нарушителя',
                'verbose_name_plural': 'Возможные цели нарушителей',
            },
        ),
        migrations.RunPython(create_scope, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='attackerscope',
            name='name',
        ),
        migrations.AddField(
            model_name='attackerscope',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.scope', verbose_name='Цель нарушителя'),
            preserve_default=False,
        ),
    ]
