# Generated by Django 4.0.5 on 2022-06-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_scope_remove_attackerscope_name_attackerscope_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackerscope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scope', verbose_name='Цель'),
        ),
    ]
