# Generated by Django 4.0.5 on 2022-06-12 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_attackerscope_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='scopes',
        ),
        migrations.AddField(
            model_name='attackerscope',
            name='attacker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.attacker', verbose_name='Нарушитель'),
            preserve_default=False,
        ),
    ]
