# Generated by Django 4.0.5 on 2022-06-12 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_attacker_scopes_attackerscope_attacker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.interface', verbose_name='Интерфейс'),
        ),
    ]
