# Generated by Django 4.0.3 on 2022-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_vulnerability_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacker',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='attacker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='threat',
            name='potential',
        ),
        migrations.AddField(
            model_name='attacker',
            name='level',
            field=models.CharField(choices=[('N4', 'Н4'), ('N3', 'Н3'), ('N2', 'Н2'), ('N1', 'Н1')], default='N4', max_length=2, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='attacker',
            name='potential',
            field=models.CharField(choices=[('HIGH', 'Высокий'), ('MEDIUM', 'Средний'), ('LOW', 'Низкий')], default='LOW', max_length=8, verbose_name='Потенциал'),
        ),
        migrations.AddField(
            model_name='threat',
            name='asset_types',
            field=models.ManyToManyField(to='app.assettype', verbose_name='Типы объектов'),
        ),
        migrations.AddField(
            model_name='threat',
            name='attackers',
            field=models.ManyToManyField(to='app.attacker', verbose_name='Нарушители'),
        ),
        migrations.AddField(
            model_name='threat',
            name='availability',
            field=models.BooleanField(default=False, verbose_name='Нарушает доступность'),
        ),
        migrations.AddField(
            model_name='threat',
            name='confidentiality',
            field=models.BooleanField(default=False, verbose_name='Нарушает конфиденциальность'),
        ),
        migrations.AddField(
            model_name='threat',
            name='description',
            field=models.TextField(max_length=1023, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='threat',
            name='integrity',
            field=models.BooleanField(default=False, verbose_name='Нарушает целостность'),
        ),
        migrations.AlterField(
            model_name='threat',
            name='name',
            field=models.CharField(max_length=1023, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(max_length=511, null=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Capabilities',
        ),
    ]
