# Generated by Django 4.0.3 on 2022-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_attacker_capabilities_remove_attacker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='bdu_id',
            field=models.IntegerField(null=True, verbose_name='Идентификатор УБИ>'),
        ),
        migrations.AlterField(
            model_name='attacker',
            name='level',
            field=models.CharField(choices=[('N4', 'Н4'), ('N3', 'Н3'), ('N2', 'Н2'), ('N1', 'Н1')], max_length=2, null=True, verbose_name='Уровень'),
        ),
    ]
