# Generated by Django 4.0.5 on 2022-06-12 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='interfaces',
            field=models.ManyToManyField(related_name='asset_type', to='app.interface', verbose_name='Интерфейсы'),
        ),
        migrations.AlterField(
            model_name='attackerscope',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker_scopes', to='app.attacker', verbose_name='Нарушитель'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='tactic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='app.tactic', verbose_name='Тактика'),
        ),
    ]
