# Generated by Django 4.0.5 on 2022-06-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_assettype_interfaces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asutpclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('BASIC', 'Базовая'), ('GOVERNMENT', 'Государственная'), ('MANUFACTURE', 'Производство')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='gisclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('BASIC', 'Базовая')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='ispdnclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('BASIC', 'Базовая'), ('GOVERNMENT', 'Государственная')], max_length=44, verbose_name='Спецификация'),
        ),
        migrations.AlterField(
            model_name='kiiclass',
            name='significance_attribute',
            field=models.CharField(choices=[('INSIGNIFICANT', 'Незначимый'), ('KZ1', 'KЗ1'), ('KZ2', 'KЗ2'), ('KZ3', 'KЗ3')], default='KZ1', max_length=13, verbose_name='Критерий значимости'),
        ),
        migrations.AlterField(
            model_name='kiiclass',
            name='specification',
            field=models.CharField(choices=[('FINANCIAL', 'Финансовая'), ('HAS_PRIVATE_WEB_RESOURCES', 'Имеет частные WEB-ресурсы'), ('HAS_PUBLIC_WEB_RESOURCES', 'Имеет публичные WEB-ресурсы'), ('DEFENCE_SYSTEM', 'Оборонная система'), ('SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA', 'Обрабатывает специальные или биометрические данные госслужащих'), ('IMPACT_ON_PUBLIC_PERCEPTION', 'Влияние на общественное сознание'), ('BASIC', 'Базовая'), ('GOVERNMENT', 'Государственная'), ('TRANSPORTATION', 'Транспорт'), ('COMMUNICATION', 'Связь'), ('INDUSTRY', 'Промышленность')], max_length=44, verbose_name='Спецификация'),
        ),
    ]
